/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Menadzer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FormaMain extends javax.swing.JFrame {
    Menadzer user;
    /**
     * Creates new form FormaMain
     */
    public FormaMain(Menadzer user) {
           initComponents();
           this.user=user;
           setTitle("ProSoft app :: "+user.getFirstname()+" "+user.getSurname());
           setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButtonLogout = new javax.swing.JButton();
        jMenuBarMainMeni = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemAddPerson = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemPrikazKlijenata = new javax.swing.JMenuItem();
        jMenuItemPorudzbine = new javax.swing.JMenuItem();
        jMenuItemKreirajRacun = new javax.swing.JMenuItem();
        jMenuItemPrikazRacuna = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jButtonLogout.setText("LOGOUT");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jMenuBarMainMeni.add(jMenu1);
        jMenuBarMainMeni.add(jMenu2);

        jMenuUser.setText("meni");

        jMenuItemAddPerson.setText("unesite novog klijenta");
        jMenuItemAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddPersonActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemAddPerson);

        jMenuItem2.setText("unesite novu porudžbinu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem2);

        jMenuItemPrikazKlijenata.setText("prikaz klijenata");
        jMenuItemPrikazKlijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazKlijenataActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemPrikazKlijenata);

        jMenuItemPorudzbine.setText("prikaz porudžbina");
        jMenuItemPorudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPorudzbineActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemPorudzbine);

        jMenuItemKreirajRacun.setText("kreiraj račun");
        jMenuItemKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajRacunActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemKreirajRacun);

        jMenuItemPrikazRacuna.setText("prikaz  računa");
        jMenuItemPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazRacunaActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemPrikazRacuna);

        jMenuBarMainMeni.add(jMenuUser);

        setJMenuBar(jMenuBarMainMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonLogout)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddPersonActionPerformed
    
        try{
        
        JDialog dialog=new JDialog(this,"Unesite klijenta", true);
        JPanel panel=new FrmUnosKlijenta();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za dodavanje klijenta!\n"+e.getMessage(),"Novi klijent",  JOptionPane.ERROR_MESSAGE);
            
            
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItemAddPersonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         try{
        
        JDialog dialog=new JDialog(this,"Unesite porudžbinu", true);
        JPanel panel=new FrmUnosPorudzbine();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za unos porudžbine!\n"+e.getMessage(),"Pretraga klijenata",JOptionPane.ERROR_MESSAGE);
            
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemPrikazKlijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazKlijenataActionPerformed
          try{
        
        JDialog dialog=new JDialog(this,"Prikažite klijente", true);
        JPanel panel=new FrmPrikazKlijenata();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za pretragu klijenata!\n"+e.getMessage(),"Pretraga klijenata",JOptionPane.ERROR_MESSAGE);
            
            
        }
    }//GEN-LAST:event_jMenuItemPrikazKlijenataActionPerformed

    private void jMenuItemPorudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPorudzbineActionPerformed
           try{
        
        JDialog dialog=new JDialog(this,"Prikažite porudzbine", true);
        JPanel panel=new FrmPrikazPorudzbina();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za pretragu porudžbina!\n"+e.getMessage(),"Pretraga poružbina",JOptionPane.ERROR_MESSAGE);
            
            
        }
    }//GEN-LAST:event_jMenuItemPorudzbineActionPerformed

    private void jMenuItemKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajRacunActionPerformed
             try{
        
        JDialog dialog=new JDialog(this,"Kreirajte račun", true);
        JPanel panel=new FrmKreirajRacun(user);
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za kreiranje računa!\n"+e.getMessage(),"Kreirajte račun",JOptionPane.ERROR_MESSAGE);
            
            
        }
    }//GEN-LAST:event_jMenuItemKreirajRacunActionPerformed

    private void jMenuItemPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRacunaActionPerformed
               try{
        
        JDialog dialog=new JDialog(this,"Prikaz računa", true);
        JPanel panel=new FrmPrikazRacuna();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za prikaz računa!\n"+e.getMessage(),"Prikaz račun",JOptionPane.ERROR_MESSAGE);
            
            
        }
    }//GEN-LAST:event_jMenuItemPrikazRacunaActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
     
        try {
          boolean signal =  Controller.getInstance().logout(user);
          
          if(signal==true){
                          JOptionPane.showMessageDialog(this, "Uspesno ste se izlogovali.","Log out",JOptionPane.INFORMATION_MESSAGE);
                          this.dispose();

          }else{
               JOptionPane.showMessageDialog(this, "Niste se uspesno izlogovali.","Log out",JOptionPane.WARNING_MESSAGE);
          }
          
          
          
          
        } catch (Exception ex) {
            Logger.getLogger(FormaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarMainMeni;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAddPerson;
    private javax.swing.JMenuItem jMenuItemKreirajRacun;
    private javax.swing.JMenuItem jMenuItemPorudzbine;
    private javax.swing.JMenuItem jMenuItemPrikazKlijenata;
    private javax.swing.JMenuItem jMenuItemPrikazRacuna;
    private javax.swing.JMenu jMenuUser;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration//GEN-END:variables
}
