/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;

import domain.Klijent;
import domain.Porudzbina;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmInformacijePorudzbine extends javax.swing.JPanel {
    Porudzbina porudzbina;
    /**
     * Creates new form FrmIzmenaPorudzbine
     */
    public FrmInformacijePorudzbine(Porudzbina porudzbina) {
        initComponents();
        this.porudzbina=porudzbina;
        prepareView(porudzbina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPoruzbina = new javax.swing.JLabel();
        jLabelKlijent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpis = new javax.swing.JTextArea();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIDK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldImeK = new javax.swing.JTextField();
        jTextFieldPrezimeK = new javax.swing.JTextField();
        jTextFieldKompanijaK = new javax.swing.JTextField();
        jTextFieldMBK = new javax.swing.JTextField();
        jTextFieldZaposleni = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabelPoruzbina.setText("PORUDZBINA");

        jLabelKlijent.setText("KLIJENT");

        jLabel2.setText("ZAPOSLENI");

        jLabel3.setText("ID");

        jLabel4.setText("opis");

        jLabel5.setText("datum (dd.mm.yyyy.)");

        jTextAreaOpis.setColumns(20);
        jTextAreaOpis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpis);

        jLabel6.setText("ID");

        jLabel7.setText("ime");

        jLabelPrezime.setText("prezime");

        jLabel8.setText("kompanija");

        jLabel9.setText("matični broj");

        jTextFieldZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZaposleniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKlijent)
                        .addGap(115, 741, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelPoruzbina)
                                                .addGap(92, 92, 92)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)))
                                            .addComponent(jLabel1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabelPrezime)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldID)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDatum)
                                    .addComponent(jTextFieldIDK)
                                    .addComponent(jTextFieldImeK)
                                    .addComponent(jTextFieldPrezimeK)
                                    .addComponent(jTextFieldKompanijaK)
                                    .addComponent(jTextFieldMBK)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoruzbina)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelKlijent)
                    .addComponent(jTextFieldIDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldImeK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezime)
                    .addComponent(jTextFieldPrezimeK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldKompanijaK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldMBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZaposleniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKlijent;
    private javax.swing.JLabel jLabelPoruzbina;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOpis;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDK;
    private javax.swing.JTextField jTextFieldImeK;
    private javax.swing.JTextField jTextFieldKompanijaK;
    private javax.swing.JTextField jTextFieldMBK;
    private javax.swing.JTextField jTextFieldPrezimeK;
    private javax.swing.JTextField jTextFieldZaposleni;
    // End of variables declaration//GEN-END:variables

    private void prepareView(Porudzbina porudzbina) {
        
        jTextFieldID.setText(String.valueOf(porudzbina.getId()));
        jTextAreaOpis.setText(porudzbina.getOpis());
        SimpleDateFormat dateFormat=new SimpleDateFormat("dd.mm.yyyy.");
        jTextFieldDatum.setText(dateFormat.format(porudzbina.getDatum()));
        
        
        jTextFieldIDK.setText(String.valueOf(porudzbina.getKlijent().getId()));
        jTextFieldImeK.setText(porudzbina.getKlijent().getIme());
        jTextFieldPrezimeK.setText(porudzbina.getKlijent().getPrezime());
        jTextFieldKompanijaK.setText(porudzbina.getKlijent().getPreduzece().toString());
        jTextFieldMBK.setText(porudzbina.getKlijent().getMaticni_broj());
        
        
        jTextFieldZaposleni.setText(porudzbina.getZaposleni().toString());
        
        
        
        jTextFieldID.setEnabled(false);
        jTextFieldIDK.setEnabled(false);
        jTextFieldZaposleni.setEnabled(false);
        
        
        
        
     
        jTextAreaOpis.setEnabled(false);
        jTextFieldDatum.setEditable(false);
        jTextFieldImeK.setEnabled(false);
        jTextFieldPrezimeK.setEnabled(false);
        jTextFieldKompanijaK.setEnabled(false);
        jTextFieldMBK.setEnabled(false);
        
        
        
        
    }

    private void izmeni() {
        jTextAreaOpis.setEnabled(true);
        jTextFieldDatum.setEditable(true);
        jTextFieldImeK.setEnabled(true);
        jTextFieldPrezimeK.setEnabled(true);
        jTextFieldKompanijaK.setEnabled(true);
        jTextFieldMBK.setEnabled(true);
    }





}
