/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;

import domain.Klijent;
import domain.Menadzer;
import domain.Porudzbina;
import domain.Racun;
import domain.StavkaRacuna;
import domain.Usluga;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import threads.ActiveThreadStavkeTable;
import ui.form.model.ModelTabeleUslugeStavke;

import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmKreirajRacun extends javax.swing.JPanel {
    Menadzer ulogovani;
    ActiveThreadStavkeTable ats;

    /**
     * Creates new form FrmKreirajRacun
     */
    public FrmKreirajRacun(Menadzer menadzer) throws Exception {
        initComponents();
        this.ulogovani=menadzer;
        prepareView();
       
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPorudzbine = new javax.swing.JComboBox<>();
        jTextFieldEvidentiraoMngr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxUsluge = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonKreirajRacun = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldOpis = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldCena = new javax.swing.JTextField();
        jButtonUbaciStavku = new javax.swing.JButton();
        jButtonUbaciGotovuStavku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUkupno = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("porudžbine");

        jLabel3.setText("evidentirao");

        jLabel4.setText("usluge");

        jLabel5.setText("stavke računa");

        jTableStavke.setBackground(new java.awt.Color(204, 204, 255));
        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("KREIRANJE RAČUNA");

        jButton1.setText("obriši stavku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonKreirajRacun.setText("KREIRAJ RAČUN");
        jButtonKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajRacunActionPerformed(evt);
            }
        });

        jLabel7.setText("ubaci novu stavku");

        jLabel8.setText("opis");

        jLabel9.setText("naziv");

        jLabel10.setText("cena");

        jButtonUbaciStavku.setText("ubaci stavku");
        jButtonUbaciStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbaciStavkuActionPerformed(evt);
            }
        });

        jButtonUbaciGotovuStavku.setText("ubaci stavku");
        jButtonUbaciGotovuStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbaciGotovuStavkuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("UKUNO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonKreirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonUbaciStavku)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel7))))
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxUsluge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBoxPorudzbine, 0, 359, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldNaziv))
                                                .addComponent(jTextFieldEvidentiraoMngr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonUbaciGotovuStavku, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jTextFieldOpis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPorudzbine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEvidentiraoMngr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUbaciGotovuStavku)
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addComponent(jButtonUbaciStavku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jButtonKreirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUbaciStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbaciStavkuActionPerformed
        ubaciStavku();
    }//GEN-LAST:event_jButtonUbaciStavkuActionPerformed

    private void jButtonUbaciGotovuStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbaciGotovuStavkuActionPerformed
        ubaciGotovuStavku();
    }//GEN-LAST:event_jButtonUbaciGotovuStavkuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            obrisiStavku();
        } catch (Exception ex) {
            Logger.getLogger(FrmKreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajRacunActionPerformed
        sacuvajRacun();
    }//GEN-LAST:event_jButtonKreirajRacunActionPerformed

    public JTextField getjTextFieldCena() {
        return jTextFieldCena;
    }

    public void setjTextFieldCena(JTextField jTextFieldCena) {
        this.jTextFieldCena = jTextFieldCena;
    }

    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    public JTextField getjTextFieldOpis() {
        return jTextFieldOpis;
    }

    public void setjTextFieldOpis(JTextField jTextFieldOpis) {
        this.jTextFieldOpis = jTextFieldOpis;
    }

    public JTable getjTableStavke() {
        return jTableStavke;
    }

    public void setjTableStavke(JTable jTableStavke) {
        this.jTableStavke = jTableStavke;
    }

    public JTextField getjTextFieldUkupno() {
        return jTextFieldUkupno;
    }

    public void setjTextFieldUkupno(JTextField jTextFieldUkupno) {
        this.jTextFieldUkupno = jTextFieldUkupno;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonKreirajRacun;
    private javax.swing.JButton jButtonUbaciGotovuStavku;
    private javax.swing.JButton jButtonUbaciStavku;
    private javax.swing.JComboBox<Porudzbina> jComboBoxPorudzbine;
    private javax.swing.JComboBox<Usluga> jComboBoxUsluge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldEvidentiraoMngr;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldOpis;
    private javax.swing.JTextField jTextFieldUkupno;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        
        fillPorudzbine();
        fillUsluge();
        fillUneditableFields();
        fillTableStavke();
      
        
      
       
    }

    private void fillPorudzbine() throws Exception {
         List<Porudzbina> porudzbine=Controller.getInstance().getPorudzbine();
        for(Porudzbina p : porudzbine){
            jComboBoxPorudzbine.addItem(p);
        }
    }

    private void fillUsluge() throws Exception {
        List<Usluga> usluge=Controller.getInstance().getUsluge();
        for(Usluga u:usluge){
            jComboBoxUsluge.addItem(u);
        }
    }

    private void fillUneditableFields() {
        jTextFieldEvidentiraoMngr.setEnabled(false);
      
       jTextFieldEvidentiraoMngr.setText(ulogovani.toString());
       
       jTextFieldUkupno.setEditable(false);
       
    }

    private void ubaciStavku() {
       
          try{
            Usluga usluga = new Usluga();
            usluga.setNaziv(jTextFieldNaziv.getText());
            usluga.setOpis(jTextFieldOpis.getText());
            usluga.setCena(Double.parseDouble(jTextFieldCena.getText()));
            
            
             Controller.getInstance().dodajStavkuUListuStavki(usluga);
         //    JOptionPane.showMessageDialog(this, "Lista stavki je uspešno ažuriran.", "Račun", JOptionPane.INFORMATION_MESSAGE);
           
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Klijent nije ažuriran!\n"+e.getMessage(), "Račun", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    private void ubaciGotovuStavku() {
          try{
            Usluga usluga = (Usluga) jComboBoxUsluge.getSelectedItem();
            
            
             Controller.getInstance().dodajStavkuUListuStavki(usluga);
           //  JOptionPane.showMessageDialog(this, "Lista stavki je uspešno ažuriran.", "Račun", JOptionPane.INFORMATION_MESSAGE);
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Klijent nije ažuriran!\n"+e.getMessage(), "Račun", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void fillTableStavke() {
       ats=new ActiveThreadStavkeTable(this);
       ats.start();
    }

    private void obrisiStavku() throws Exception {
       
        int signal=jTableStavke.getSelectedRow();
        
        if(signal==-1){
             JOptionPane.showMessageDialog(this, "Morate odabrati stavku za brisanje!\n", "Račun", JOptionPane.ERROR_MESSAGE);
        }else{
            
            ModelTabeleUslugeStavke mtus=(ModelTabeleUslugeStavke) jTableStavke.getModel();
            List<StavkaRacuna> stavke=mtus.getStavke();
            StavkaRacuna stavkaZaBrisanje = stavke.get(signal);
            Controller.getInstance().obrisiStavkuIzListe(stavkaZaBrisanje);
        }
        
        
        
        
    }

    private void sacuvajRacun() {
     //metoda sacuvaj racun koja cuva racun i sve njegove stavke
          try{
            Racun racun=new Racun();
            racun.setDatum(new Date());
            racun.setMenadzer(ulogovani);
            racun.setPorudzbina((Porudzbina) jComboBoxPorudzbine.getSelectedItem());
            racun.setStavkeRacuna(Controller.getInstance().getStavke());
            
            Double ukupnoD=Double.parseDouble(jTextFieldUkupno.getText());
            racun.setUkupno(ukupnoD);
            //nema id!!!
            
            
            
            if(Double.parseDouble(jTextFieldUkupno.getText())!=0){
                  Controller.getInstance().kreirajRacun(racun);
             JOptionPane.showMessageDialog(this, "Sistem je zapamtio račun.", "Unesite račun.", JOptionPane.INFORMATION_MESSAGE);
              this.getTopLevelAncestor().setVisible(false);  
                
            }else{
               JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti račun.", "Unesite račun.", JOptionPane.ERROR_MESSAGE);

            }
            
            
            
           
            
           
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Račun nije sačuvan!\n"+e.getMessage(), "Unesite račun.", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
}
