/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;

import domain.Klijent;
import java.awt.Dialog;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.form.model.ModelTabeleKlijenti;
import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmPrikazKlijenata extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrikazKlijenata
     */
    public FrmPrikazKlijenata() throws Exception {
        initComponents();
        prepareView();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPretraga = new javax.swing.JLabel();
        jLabelPreduzece = new javax.swing.JLabel();
        jTextFieldPreduzece = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKlijenti = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabelPretraga.setText("pretraga klijenata");

        jLabelPreduzece.setText("preduzece");

        jButtonPretrazi.setText("pretražite");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableKlijenti.setBackground(new java.awt.Color(204, 204, 255));
        jTableKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKlijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKlijentiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKlijenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPretraga)
                        .addGap(177, 177, 177)
                        .addComponent(jLabelPreduzece)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPreduzece, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPretrazi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPreduzece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi)
                    .addComponent(jLabelPreduzece)
                    .addComponent(jLabelPretraga))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        
       String StringPred=jTextFieldPreduzece.getText();
        try {
            pretraziPoKriterijumu(StringPred);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex, "Forma za prikaz klijenata.",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jTableKlijentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKlijentiMouseClicked
        // TODO add your handling code here:
        izmeniIzabranogKorisnika();
    }//GEN-LAST:event_jTableKlijentiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabelPreduzece;
    private javax.swing.JLabel jLabelPretraga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKlijenti;
    private javax.swing.JTextField jTextFieldPreduzece;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
       
         List<Klijent> klijenti = Controller.getInstance().getKlijenti();
        ModelTabeleKlijenti mtp = new ModelTabeleKlijenti(klijenti);
        jTableKlijenti.setModel(mtp);
    }

    private void pretraziPoKriterijumu(String StringPred) throws Exception {
        
        
        List<Klijent> klijentiFiltrirani = Controller.getInstance().getKlijentiFilter(StringPred);
        ModelTabeleKlijenti mtp = new ModelTabeleKlijenti(klijentiFiltrirani);
        jTableKlijenti.setModel(mtp);
        
        if(klijentiFiltrirani.size()==0){
       JOptionPane.showMessageDialog(this,"Sistem ne može da nađe klijente po zadatoj vrednosti." , "Prikaz klijenata", JOptionPane.INFORMATION_MESSAGE); 

        }else{
       JOptionPane.showMessageDialog(this,  "Sistem je našao klijente po zadatoj vrednosti.", "Prikaz klijenata", JOptionPane.INFORMATION_MESSAGE); 

        }
        
       
    }

    private void izmeniIzabranogKorisnika() {
        int signal = jTableKlijenti.getSelectedRow();
       
           
            ModelTabeleKlijenti model = (ModelTabeleKlijenti) jTableKlijenti.getModel();
            List<Klijent> klijenti = model.getKlijenti();
            Klijent klijentZaIzmenu=klijenti.get(signal);
            JOptionPane.showMessageDialog(this, "Sistem je učitao klijenta!", "Prikaz klijenata", JOptionPane.INFORMATION_MESSAGE);  
           try{
        
       JDialog dialog=new JDialog((JFrame)null,"Izmena klijenta", true);
        JPanel panel=new FrmIzmeniKlijenta(klijentZaIzmenu);
       dialog.add(panel);
        dialog.pack();
       dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za izmenu klijenta!\n"+e.getMessage(),"Izmena klijenta",  JOptionPane.ERROR_MESSAGE);
            
            
        }
            
     
    }

}
