/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;

import domain.Klijent;
import domain.Porudzbina;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.form.model.ModelTabeleKlijenti;
import ui.form.model.ModelTabelePorudzbine;
import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmPrikazPorudzbina extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrikazPorudzbina
     */
    public FrmPrikazPorudzbina() throws Exception {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPorudzbine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDPretraga = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePorudzbine = new javax.swing.JTable();
        jButtonIzmeni = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabelPorudzbine.setText("pretraga porudžbina");

        jLabel1.setText("ID");

        jButtonPretrazi.setText("PRETRAŽI");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTablePorudzbine.setBackground(new java.awt.Color(204, 204, 255));
        jTablePorudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePorudzbine);

        jButtonIzmeni.setText("PRIKAŽI");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPorudzbine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPretrazi)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButtonIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorudzbine)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
      
        
        int idP=Integer.valueOf(jTextFieldIDPretraga.getText());
        
    
        try {
            filtrirajPorudzbine(idP);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrikazPorudzbina.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
        
        
        
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
       izmenaPorudzbine();
      
    }//GEN-LAST:event_jButtonIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPorudzbine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePorudzbine;
    private javax.swing.JTextField jTextFieldIDPretraga;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
       
        List<Porudzbina> porudzbine=Controller.getInstance().getPorudzbine();
        ModelTabelePorudzbine mtp = new ModelTabelePorudzbine(porudzbine);
        jTablePorudzbine.setModel(mtp);
        
        
      }

    private void filtrirajPorudzbine(int idP) throws Exception {
          List<Porudzbina> porudzbine=Controller.getInstance().getPorudzbineFilter(idP);
        ModelTabelePorudzbine mtp = new ModelTabelePorudzbine(porudzbine);
        jTablePorudzbine.setModel(mtp);
        
        if(porudzbine.size()==0){
      JOptionPane.showMessageDialog(this, "Sistem ne može da nađe porudžbine po zadatoj vrednosti.", "Prikaz porudžbina", JOptionPane.ERROR_MESSAGE); 

        }else{
        JOptionPane.showMessageDialog(this, "Sistem je našao porudžbine po zadatoj vrednosti.", "Prikaz porudžbina", JOptionPane.INFORMATION_MESSAGE); 
  
        }
        
        
        
    }

    private void izmenaPorudzbine() {
          int signal = jTablePorudzbine.getSelectedRow();
        if(signal==-1){
             JOptionPane.showMessageDialog(this, "Sistem ne može da učita porudžbinu.", "Prikaz porudžbina", JOptionPane.ERROR_MESSAGE); 
        }else{
            ModelTabelePorudzbine model = (ModelTabelePorudzbine) jTablePorudzbine.getModel();
            List<Porudzbina> porudzbine = model.getPorudzbine();
            Porudzbina porudzbinaZaIzmenu=porudzbine.get(signal);
            
           try{
        
        JDialog dialog=new JDialog((JFrame)null,"Prikaz porudzbine", true);
        JPanel panel=new FrmInformacijePorudzbine(porudzbinaZaIzmenu);
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
         JOptionPane.showMessageDialog(this, "Sistem je učitao porudžbinu.", "Prikaz porudžbina", JOptionPane.INFORMATION_MESSAGE); 
        dialog.setVisible(true);
        
  

        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za izmenu porudžbine!\n"+e.getMessage(),"Prikaz porudžbine",  JOptionPane.ERROR_MESSAGE);
            
            
        }
            
        }
    }
}
