/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;


import domain.Racun;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.form.model.ModelTabeleRacuni;

import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmPrikazRacuna extends javax.swing.JPanel {

    /**
     * Creates new form PrikazRacuna
     */
    public FrmPrikazRacuna() throws Exception {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPretraga = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacuni = new javax.swing.JTable();
        jButtonIzbrisi = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("klijent (ime)");

        jLabel2.setText("računi");

        jButtonPretrazi.setText("pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableRacuni.setBackground(new java.awt.Color(204, 204, 255));
        jTableRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRacuni);

        jButtonIzbrisi.setText("izaberi");
        jButtonIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzbrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIzbrisi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(39, 39, 39)
                            .addComponent(jTextFieldPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonPretrazi))
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIzbrisi)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            pretraziRacune();
        } catch (Exception ex) {
            Logger.getLogger(FrmPrikazRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzbrisiActionPerformed
       
        
      
      prikaziRacun();     
      
        
    }//GEN-LAST:event_jButtonIzbrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzbrisi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRacuni;
    private javax.swing.JTextField jTextFieldPretraga;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {


         List<Racun> racuni = Controller.getInstance().getRacuni();
        ModelTabeleRacuni mtr = new ModelTabeleRacuni(racuni);
        jTableRacuni.setModel(mtr);

    }

    private void pretraziRacune() throws Exception {
       String imePrezime=jTextFieldPretraga.getText();
       
         List<Racun> racuni = Controller.getInstance().getRacuniFilter(imePrezime);
        ModelTabeleRacuni mtr = new ModelTabeleRacuni(racuni);
        jTableRacuni.setModel(mtr);
        
        if(racuni.size()==0){
             JOptionPane.showMessageDialog(this, "Sistem ne može da nađe račune po zadatoj vrednosti.", "Brisanje računa", JOptionPane.INFORMATION_MESSAGE);
        }else{
             JOptionPane.showMessageDialog(this, "Sistem je našao račune po zadatoj vrednosti.", "Brisanje računa", JOptionPane.INFORMATION_MESSAGE);

        }
        
        
        

       
    }


    private void prikaziRacun() {
         int signal = jTableRacuni.getSelectedRow();
        if(signal==-1){
             JOptionPane.showMessageDialog(this, "Sistem ne može da učita racun!", "Prikaz računa", JOptionPane.ERROR_MESSAGE); 
        }else{
           
            ModelTabeleRacuni model = (ModelTabeleRacuni) jTableRacuni.getModel();
            List<Racun> racuni = model.getRacuni();
            Racun racunZaIzmenu=racuni.get(signal);
            JOptionPane.showMessageDialog(this, "Sistem je učitao racun!", "Prikaz računa", JOptionPane.INFORMATION_MESSAGE);  
           try{
        
       JDialog dialog=new JDialog((JFrame)null,"Brisanje računa", true);
       JPanel panel=new FrmPrikaziRacun(racunZaIzmenu);
       dialog.add(panel);
       dialog.pack();
       dialog.setLocationRelativeTo(this);
       dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
       dialog.setVisible(true);
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Greška u inicijalizaciji forme za brisanje racuna!\n"+e.getMessage(),"Brisanje računa",  JOptionPane.ERROR_MESSAGE);
            
            
        }
            
        }
    }


}
