/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.form;

import domain.Klijent;
import domain.Porudzbina;
import domain.Zaposleni;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import uicontroller.Controller;

/**
 *
 * @author Acer
 */
public class FrmUnosPorudzbine extends javax.swing.JPanel {

    /**
     * Creates new form FrmUnosPorudzbine
     */
    public FrmUnosPorudzbine() throws Exception {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpisUsluge = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpisUsluge = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxZaduzenja = new javax.swing.JComboBox<>();
        jButtonSacuvaj = new javax.swing.JButton();
        jLabelKlijent = new javax.swing.JLabel();
        jComboBoxKlijenti = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabelOpisUsluge.setText("opis usluge");

        jLabelDatum.setText("datum (dd.mm.yyyy.)");

        jTextAreaOpisUsluge.setColumns(20);
        jTextAreaOpisUsluge.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpisUsluge);

        jLabel2.setText("zadužen");

        jButtonSacuvaj.setText("SAČUVAJ");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jLabelKlijent.setText("klijent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpisUsluge)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelKlijent))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxZaduzenja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDatum)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButtonSacuvaj))
                            .addComponent(jComboBoxKlijenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpisUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKlijent)
                    .addComponent(jComboBoxKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonSacuvaj)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
      try{
                                                           
            Porudzbina porudzbina = new Porudzbina();
            porudzbina.setOpis(jTextAreaOpisUsluge.getText());
            
            String datumStr=jTextFieldDatum.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd.mm.yyyy.");
            java.util.Date datum = null;
            
            try{
            datum=dateFormat.parse(datumStr);
            porudzbina.setDatum(datum);
            }catch (ParseException ex){
                throw  ex;
            }
            
            
            porudzbina.setZaposleni((Zaposleni) jComboBoxZaduzenja.getSelectedItem());
            
            porudzbina.setKlijent((Klijent) jComboBoxKlijenti.getSelectedItem());
           
            
             Controller.getInstance().kreirajPorudzbinu(porudzbina);
             JOptionPane.showMessageDialog(this, "Sistem je zapamtio porudžbinu!\n", "Unesite porudžbinu", JOptionPane.INFORMATION_MESSAGE);
             this.getTopLevelAncestor().setVisible(false);
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti porudžbinu!\n","Unesite porudžbinu", JOptionPane.ERROR_MESSAGE);
        }
      
        
        
        
    }//GEN-LAST:event_jButtonSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Klijent> jComboBoxKlijenti;
    private javax.swing.JComboBox<Zaposleni> jComboBoxZaduzenja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelKlijent;
    private javax.swing.JLabel jLabelOpisUsluge;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOpisUsluge;
    private javax.swing.JTextField jTextFieldDatum;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {


        fillWithZaposleni();
        fillWithKlijenti();
        




    }

    private void fillWithZaposleni() throws Exception {
         List<Zaposleni> zaposleni = Controller.getInstance().getZaposleni();
        for(Zaposleni z:zaposleni){
            jComboBoxZaduzenja.addItem(z);
        }
    }

    private void fillWithKlijenti() throws Exception {
         List<Klijent> klijenti = Controller.getInstance().getKlijenti();
        for(Klijent k:klijenti){
            jComboBoxKlijenti.addItem(k);
        }
    }
}
